### ISSUE TITLE
Crash because of non-existent shape function layout

### ISSUE THREAD

**Issue by hiptmair** [craffael/lehrfempp#119]
See [comment on Gitlab](https://gitlab.math.ethz.ch/ralfh/npdecodes/merge_requests/38#note_4177). Missing shape function specifications have to be checked.

**Comment by hiptmair** [comment]
I have added the required checks and assertions in branch `bugfix_uscalfe`.

**Comment by craffael** [comment]
This is resolved and published through hunter.

**Comment by anianruoss** [comment]
The same problem appears in `lf::uscalfe::MeshFunctionL2NormDifference`.

**Comment by craffael** [comment]
Okay, I guess you get a `NotInitialized` assert thrown from `precomputed_scalar_reference_finite_element.h`?

**Comment by craffael** [comment]
I've pushed another commit so that you get a nicer error message. But it's gonna take a moment until it's available on hunter.

**Comment by anianruoss** [comment]
Actually, I realized that my `loc_comp_norms.h` file hasn't been updated to the latest release of Hunter, even though the rest of the project has (which is why I was still getting segmentation faults). How can I force Hunter to delete and re-download the latest version?

**Comment by anianruoss** [comment]
After deleting my `~/.hunter` directory and rebuilding LehrFEM on a fresh clone of the `npdecodes` repository I still get a segmentation fault. For some reason the LehrFEM version includes the fixed `ReactionDiffusionElementMatrixProvider` with:

```c++
ReactionDiffusionElementMatrixProvider<SCALAR, DIFF_COEFF, REACTION_COEFF>::
    ReactionDiffusionElementMatrixProvider(
        std::shared_ptr<UniformScalarFESpace<SCALAR>> fe_space,
        DIFF_COEFF alpha, REACTION_COEFF gamma)
    : alpha_(std::move(alpha)), gamma_(std::move(gamma)), fe_precomp_() {
  for (auto ref_el : {base::RefEl::kTria(), base::RefEl::kQuad()}) {
    auto fe = fe_space->ShapeFunctionLayout(ref_el);
    // Check whether shape functions for that entity type are available
    if (fe != nullptr) {
      // Precompute cell-independent quantities based on quadrature rules
      // with twice the degree of exactness compared to the degree of the
      // finite element space.
      fe_precomp_[ref_el.Id()] = PrecomputedScalarReferenceFiniteElement(
          fe, quad::make_QuadRule(ref_el, 2 * fe->Degree()));
    }
  }
}
```

but the constructor of `MeshFunctionL2NormDifference` doesn't check `if (fe != nullptr)`:

```c++
 MeshFunctionL2NormDifference(
      const std::shared_ptr<const UniformScalarFESpace<double>> &fe_space,
      FUNCTOR u, quad::quadDegree_t loc_quad_order)
      : u_(std::move(u)) {
    for (auto ref_el : {base::RefEl::kTria(), base::RefEl::kQuad()}) {
      auto fe = fe_space->ShapeFunctionLayout(ref_el);
      fe_precomp_[ref_el.Id()] =
          PrecomputedScalarReferenceFiniteElement<double>(
              std ::move(fe), quad ::make_QuadRule(ref_el, loc_quad_order));
    }
  }
```

Weirdly, #120 contained the correct version of MeshFunctionL2NormDifference. @craffael do you know what is going on here?

**Comment by craffael** [comment]
Have you updated your hunter gate command?
```
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.136.tar.gz"
    SHA1 "1ed14d1b60393bddffff44c5527f17b42596eb89"
)
```

**Comment by craffael** [comment]
The fix for MeshFunctionL2 norm is not yet published via hunter, I will try to do it in 2-3 hours.

**Comment by anianruoss** [comment]
> Have you updated your hunter gate command?
> 
> ```
> HunterGate(
>     URL "https://github.com/ruslo/hunter/archive/v0.23.136.tar.gz"
>     SHA1 "1ed14d1b60393bddffff44c5527f17b42596eb89"
> )
> ```

I was using `v0.23.135`. Do I also need to update the `lehrfempp VERSION` in `cmake/Hunter/config.cmake`? The current version is `0.7.12`. 


> The fix for MeshFunctionL2 norm is not yet published via hunter, I will try to do it in 2-3 hours.

Okay, thank you.

**Comment by craffael** [comment]
Ah yes if you set the veesion manually, you have to update it to 0.7.13. And version 0.23.135 of hunter should suffice

**Comment by anianruoss** [comment]
Updating to `0.7.13` did the trick. Where can I find the latest version in the future?

**Comment by craffael** [comment]
https://github.com/craffael/lehrfempp/releases but be careful, sometimes a version is shown there but it is not yet available on hunter (you will receive an error message). At the moment the most up2date version is 0.7.13

**Comment by anianruoss** [comment]
Great, thanks!
